### ISSUE TITLE
Weitere Dokumentation

### ISSUE THREAD

**Issue by behnkec** [Methods-Berlin/RLernplattform#102]
Bei folgenden Themen fehlen noch Dokumentationen:
- [x] renv
- [x] Docker

**Comment by behnkec** [comment]
@jhorzek musstest du bei renv noch was machen, nachdem du das Paket installiert hattest oder wurden die dependencies automatisch geladen?

**Comment by jhorzek** [comment]
Ich musste renv::restore() ausführen, um die Pakete in der passenden Version installiert werden. Alles andere lief dann automatisch
