### ISSUE TITLE
Neugliederung der Abschnitte

### ISSUE THREAD

**Issue by manuelarnold** [Methods-Berlin/RLernplattform#107]
Hey! Hier sind einige Ideen, die uns heute zur Neugliederung der Abschnitte gekommen sind. Lass uns hier weiter Ideen sammeln und beim nächsten Treffen gemeinsam besprechen. Bisher ist das alles nichts Großes.

- "Einführung in RStudio" umbenennen in „Übersicht über die Oberfläche“ oder einen besseren Namen und vor „Einführung in R“ ziehen.
- Neuer Abschnitt in den Weiterführenden Themen in R mit einer Kurzvorstellung des Tidyverses (pipe operator und einige Grundfunktionen des Tidyverse) und prominentem Link zu R for Data Science. Ich habe etwas Material dafür. Allerdings habe ich gerade keine Zeit den Abschnitt zu schreiben.
- Im Ersten Kapitel „Einführung in R“ dann Basis-R-Funktionen außer für spezielle Anwendungen wie Plots einsetzen. Im zweiten Kapitel dann mehr Tidyverse.
- „Datenvorbereitung“ dann hinter Tidyverse-Abschnitt in den weiterführenden Links verschieben. In Datenvorbereitung dann stärker oder nur noch Tidy-Verse nutzen.  
- "Fehlende Werte" könnte man auch in die Weiterführenden Themen verschieben oder sogar als Unterabschnitt von Datenvorbereitung. Oder man teilt Datenvorbereitung in einzelne Abschnitte. Ist ja ein riesiges Thema.

**Comment by MarcelaHa** [comment]
Hallo! Hier auch meine Gedanken bzw. Verbesserungsvorschläge zu dem woran ich bisher gearbeitet habe: 
- Den Abschnitt 3.2.3 "Objekte" in "Einführung in R" am Anfang, vor "Datentypen" und "Datenstrukturen" schieben. 
- Den Abschnitt 3.2. "Daten" ggf. vor 3.1"Funktionen und Pakete".
- Ein Teil des Inhalts zu 3.1.2 "Pakete" von "Einführung in R" zu "Pakete" schieben.

**Comment by jhorzek** [comment]
Vorschlag von @manuelarnold: Wir bauen eine zusätzliche Seite vor der Einführung in R ein, die ein motivierendes Beispiel für die Nutzung von R und RStudio liefert. Beispiel: Bachelorarbeit mit R durchführen -> Datenanalyse und Plots erstellen. Im Beispiel sollen die auf der Plattform gelehrten Themen genutzt werden. Nach Abschluss der Übungen, sollen Studierende die Analyse selbst replizieren können.

**Comment by manuelarnold** [comment]
Wir könnten außerdem vielleicht noch eine kurze Übersicht über alle Kurse im Bachelor und Master geben, in denen viel R benutzt wird. Also z.B. Diagnostik, Exprak, Abschlussarbeiten, usw. Die Idee ist den Studierenden schon ab Tag 1 einzubläuen, dass sie R nicht nur in der Methodenlehre sondern in ihrem ganzen Studium benutzen werden.
