### ISSUE TITLE
R Crash Course Ausarbeiten

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#118]
- [x] @MarcelaHa: Einführung in Pipe-Operator (`|>`)
  - [x] alternative tidyverse pipe (`%>%`) erwähnen
- [x] @jhorzek: Fehlermeldungen
- [x] @manuelarnold Hilfe aus dem Internet
- [x] @behnkec best practices
  - [x]  Link zu R for data science: http://adv-r.had.co.nz/Style.html

Themen sollten höchstens 1-2 Seiten lang sein

**Comment by manuelarnold** [comment]
Habe die Seite für Hilfe aus dem Internet erstellt. Änderungen und Verbesserungen sind willkommen.
