### ISSUE TITLE
Installationsseite überarbeiten

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#119]
- Quick Start: kurze Installationsinstruktionen an Anfang des Crash Course
  - Wir könnten hier auch auf die RStudio cloud verweisen, falls die Installation nicht klappt
- details der Installation ans Ende der Webseite verschieben und im Quick Start verlinken

**Comment by manuelarnold** [comment]
Ist erledigt und kann gerne nochmal durchgesehen werden.
