### ISSUE TITLE
Design der Startseite

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#13]
Ich habe leider bisher noch keine Idee, wie wir das Design der bisherigen Startseite (http://methods-berlin.com/de/r-lernplattform/) für die neue Bookdown Website übernehmen können. Ich fände es gut, wenn es zu jedem Kapitel Übungen und ein FAQ geben würde. Damit würde aber die Trennung von Thema, Übung und FAQ unserer bisherigen Website wegfallen. Wir müssten also auch die Startseite noch mal anpassen. Clara und Britta, könntet Ihr Euch bitte Gedanken manchen, wie die Startseite aussehen könnte? Schaut am besten mal nach anderen Bookdown-Projekten, um eine Idee zu bekommen, was man da so implementieren kann. 

Lasst Euch für diese Aufgabe gerne Zeit; die Startseite selbst kann auch erst mal nur ein Provisorium sein.

**Comment by behnkec** [comment]
@jhorzek ich habe hier https://github.com/Methods-Berlin/RLernplattform/commit/fe3e349d2c484be669ea08118feedc6ebcf18385 mal einen ersten Aufschlag für die Startseite gemacht.

**Comment by jhorzek** [comment]
Vielen Dank!! Ich habe die Startseite noch etwas angepasst (siehe https://github.com/Methods-Berlin/RLernplattform/tree/behnkec-startseite). Du kannst gerne alles nochmal überarbeiten, wenn Du ein besseres Design im Sinn hast :). Andernfalls kannst Du auch gleich in Main mergen.
