### ISSUE TITLE
Vergleich: Pakete.qmd

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#35]
Bitte vergleiche die im Titel des Issues genannte Seite mit der unter http://methods-berlin.com/de/r-lernplattform/. Lade hierfür die aktuellste Version des "docs" Ordners von hier herunter: https://github.com/Methods-Berlin/RLernplattform/actions/runs/4086166490. Extrahiere die Datein und öffne sie in einem Browser.

Besonderes Augenmerk sollte dabei auch auf folgendes gelegt werden:

- [x] Sind die Überschriften auf dem richtigen Level?
- [x] funktionieren die Links?
- [x] Sind alle Bilder richtig eingebunden?
- [x] funktioniert der R-Code und sehen die Plots richtig aus?
- [x] Tauchen irgendwo Warnungen etc auf, die dort nicht sein sollten?
- [x] Sind Textpassagen in der Randnotiz, die eigentlich in den Haupttext gehören?

Falls Fehler auffallen:

1. Wenn es ein einfacher Fehler ist (z.B. Schreibfehler, Überschrift auf der falschen Ebene, ...), dann können diese gerne direkt in der .qmd Datei behoben werden.
2. Wenn es kompliziertere Fehler sind oder Du nicht weißt, wie man den Fehler lösen kann, dann bitte unten einen Kommentar schreiben und mich mit @jhorzek erwähnen. Dann schaue ich, ob ich das Problem lösen kann.

Hinweis: Ich habe einige Überschriften angepasst (z.B. habe "## 1. Überschrift" zu "## Überschrift" geändert). Diese Anpassungen bitte nicht rückgängig machen!

**Comment by Methods-Berlin** [comment]
Hinweis: Die Webseite ist jetzt [online](https://methods-berlin.github.io/RLernplattform/). Bitte vergleiche die alte R-Lernplattform (http://methods-berlin.com/de/r-lernplattform/) mit unserer neuen Version unter https://methods-berlin.github.io/RLernplattform/ .

**Comment by behnkec** [comment]
@jhorzek bei mir funktioniert bei Pakete das Inhaltsverzeichnis nicht richtig (es wird nur die erste Ebene angezeigt und der blaue Balken bewegt sich nicht mit), bei allen anderen Themen funktioniert es aber einwandfrei. Ist das bei dir auch so?

**Comment by jhorzek** [comment]
Bei mir hat das Inhaltsverzeichnis auch nicht funktioniert. Scheinbar war ein Link in einer der Überschriften das Problem: https://github.com/Methods-Berlin/RLernplattform/commit/37413d385908f0c80b86e6a2e447621dc1a5b5c4
