### ISSUE TITLE
Vergleich: Fehlermeldungen.qmd

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#37]
Bitte vergleiche die im Titel des Issues genannte Seite mit der unter http://methods-berlin.com/de/r-lernplattform/. Lade hierfür die aktuellste Version des "docs" Ordners von hier herunter: https://github.com/Methods-Berlin/RLernplattform/actions/runs/4086166490. Extrahiere die Datein und öffne sie in einem Browser.

Besonderes Augenmerk sollte dabei auch auf folgendes gelegt werden:

- [x] Sind die Überschriften auf dem richtigen Level?
- [x] funktionieren die Links?
- [x] Sind alle Bilder richtig eingebunden?
- [x] funktioniert der R-Code und sehen die Plots richtig aus?
- [x] Tauchen irgendwo Warnungen etc auf, die dort nicht sein sollten?
- [x] Sind Textpassagen in der Randnotiz, die eigentlich in den Haupttext gehören?

Falls Fehler auffallen:

1. Wenn es ein einfacher Fehler ist (z.B. Schreibfehler, Überschrift auf der falschen Ebene, ...), dann können diese gerne direkt in der .qmd Datei behoben werden.
2. Wenn es kompliziertere Fehler sind oder Du nicht weißt, wie man den Fehler lösen kann, dann bitte unten einen Kommentar schreiben und mich mit @jhorzek erwähnen. Dann schaue ich, ob ich das Problem lösen kann.

Hinweis: Ich habe einige Überschriften angepasst (z.B. habe "## 1. Überschrift" zu "## Überschrift" geändert). Diese Anpassungen bitte nicht rückgängig machen!

**Comment by Methods-Berlin** [comment]
Hinweis: Die Webseite ist jetzt [online](https://methods-berlin.github.io/RLernplattform/). Bitte vergleiche die alte R-Lernplattform (http://methods-berlin.com/de/r-lernplattform/) mit unserer neuen Version unter https://methods-berlin.github.io/RLernplattform/ .

**Comment by behnkec** [comment]
- [ ] 7.1.1 unter dem Bild die Wörter in Klammern fett
- [ ] Link detaillierte Einführung genauer spezifizieren
- [ ] 7.2 Syntaxfehler nach ":" fett
- [ ] 7.3 Wir könne dafür Suchmaschinen "oder"
- [ ] 7.4 eine Ebene niedriger (das a) weg machen?)
- [ ] 7.8 Link zu Tipps zum Suchen im Internet 404
- [ ] in englisch suchen -> auf Englisch suchen

**Comment by behnkec** [comment]
@jhorzek die Website zu „Tipps zum Suchen im Internet“ existiert nicht mehr. Ich würde eine von denen als Ersatz vorschlagen:

- https://www.lifewire.com/web-search-tricks-to-know-4046148
- https://medium.com/marketing-and-entrepreneurship/12-powerful-google-hacks-to-make-you-a-power-searcher-763c71f3d8e1
- https://zapier.com/blog/advanced-google-search-tricks/

Was denkst du?

**Comment by jhorzek** [comment]
Ich finde https://www.lifewire.com/web-search-tricks-to-know-4046148 am anschaulichsten. Alternativ finde ich die Seite ganz gut: https://www.theguardian.com/technology/2016/jan/15/how-to-use-search-like-a-pro-10-tips-and-tricks-for-google-and-beyond
