### ISSUE TITLE
Vergleich: Grafiken.qmd

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#41]
Bitte vergleiche die im Titel des Issues genannte Seite mit der unter http://methods-berlin.com/de/r-lernplattform/. Lade hierfür die aktuellste Version des "docs" Ordners von hier herunter: https://github.com/Methods-Berlin/RLernplattform/actions/runs/4086166490. Extrahiere die Datein und öffne sie in einem Browser.

Besonderes Augenmerk sollte dabei auch auf folgendes gelegt werden:

- [x] Sind die Überschriften auf dem richtigen Level?
- [x] funktionieren die Links?
- [x] Sind alle Bilder richtig eingebunden?
- [x] funktioniert der R-Code und sehen die Plots richtig aus?
- [x] Tauchen irgendwo Warnungen etc auf, die dort nicht sein sollten?
- [x] Sind Textpassagen in der Randnotiz, die eigentlich in den Haupttext gehören?

Falls Fehler auffallen:

1. Wenn es ein einfacher Fehler ist (z.B. Schreibfehler, Überschrift auf der falschen Ebene, ...), dann können diese gerne direkt in der .qmd Datei behoben werden.
2. Wenn es kompliziertere Fehler sind oder Du nicht weißt, wie man den Fehler lösen kann, dann bitte unten einen Kommentar schreiben und mich mit @jhorzek erwähnen. Dann schaue ich, ob ich das Problem lösen kann.

Hinweis: Ich habe einige Überschriften angepasst (z.B. habe "## 1. Überschrift" zu "## Überschrift" geändert). Diese Anpassungen bitte nicht rückgängig machen!

**Comment by Methods-Berlin** [comment]
Hinweis: Die Webseite ist jetzt [online](https://methods-berlin.github.io/RLernplattform/). Bitte vergleiche die alte R-Lernplattform (http://methods-berlin.com/de/r-lernplattform/) mit unserer neuen Version unter https://methods-berlin.github.io/RLernplattform/ .

**Comment by behnkec** [comment]
- [ ] Violinenplot Link
- [ ] Link zu cheat sheets (404) (im toggle cheat sheet)
- [ ] Link mehr als drei Variablen (im toggle Beispieldatensatz)
- [ ] 10.1 Link Datenstruktur
- [ ] Überschrift 10.2.1 1. Ebene und 2. Ebene hinzufügen (Bezugnahme auf den Text)
- [ ] aside 'Wir können' (Grundlegendes Koordinatensystem) weiter unten
- [ ] aside 'Hier sehen wir' (Art der Grafik) weiter unten
- [ ] 10.3.1 'Später' Link
- [ ] 10.3.1.1 absolute und relative fett oder unterstrichen oder so (Unterschied deutlich machen)
- [ ] **Warnung** (The dot-dot notation (`..prop..`) was deprecated in ggplot2 3.4.0.  Please use `after_stat(prop)` instead.)
- [ ] 'gestapelte' fett
- [ ] aside 'Auf die Integration' (Balkendiagramm) weiter unten
- [ ] Richtlinien Histogramme: 'nicht mehr als 20 Kategorien' fett
- [ ] 10.4.1 'Später' Link
- [ ] aside 'Hier wird das Indexieren' Hier Link -> wohin (Violinenplot)
- [ ] 10.4.1.2 Bilder nebeneinander?
- [ ] 10.4.1.3 aside 'Hier' link -> wohin
- [ ]  10.4.2.1 aside Farben Link
- [ ] 10.4.2.3 **Warnung** `geom_smooth()` using formula = 'y ~ x'
- [ ] 10.5.1.1 Überschrift **
- [ ] 10.5.1.1 **Warnung** `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
- [ ] 10.5.1.1 aside Link [vor der Verarbeitung]
- [ ] 10.5.1.1 Cheat Sheet Link funktioniert nicht
- [ ] 10.5.2 tog Vergleich unseres Dataframes -> Tabelle hübscher machen
- [ ] **Warnung** Missing alluvia for some stratum combinations.
- [ ] **Warning** in to_lodes_form(data = data, axes = axis_ind, discern = params$discern): Some strata appear at multiple axes.
- [ ] bei Modifikationen könnten manche Überschriften noch eine Ebene runter
- [ ] 10.6.2 Umrandung und Füllung fett (erster Stichpunkt)
- [ ] 10.6.2 aside weiter runter
- [ ] Tabelle zu statische/variable Farben: Bilder funktionieren nicht
- [ ] 10.6.12.1 Bilder neben einander?
- [ ] 10.7.2 Bilder neben einander?
- [ ] 10.8 aside Hier Link
- [ ] 10.8 Bilder neben einander
- [ ] 10.9 aside Hier Link
- [ ] 10.10 **Warnung**
- [ ] 10.12.1 Textfarbe
- [ ] 10.12.2 Textfarbe

**Comment by behnkec** [comment]
@jhorzek Bei der alten Website kann man bei Codeblöcken, die im Text angezeigt werden, auf die Funktionen clicken und wird dann zur Dokumentation weitergeleitet. Das ist ganz cool, gibt es eine Möglichkeit, wie wir das auch implementieren können?

**Comment by jhorzek** [comment]
Das war mir noch gar nicht aufgefallen. Leider weiß ich auch nicht,  ob wir das irgendwie automatisch einfügen können.

**Comment by behnkec** [comment]
@jhorzek  in der Tabelle zu statische/variable Farben habe ich die Bilder leider nicht zum Laufen gebracht
