### ISSUE TITLE
Vergleich: Voraussetzungspruefung.qmd

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#43]
Bitte vergleiche die im Titel des Issues genannte Seite mit der unter http://methods-berlin.com/de/r-lernplattform/. Lade hierfür die aktuellste Version des "docs" Ordners von hier herunter: https://github.com/Methods-Berlin/RLernplattform/actions/runs/4086166490. Extrahiere die Datein und öffne sie in einem Browser.

Besonderes Augenmerk sollte dabei auch auf folgendes gelegt werden:

- [x] Sind die Überschriften auf dem richtigen Level?
- [x] funktionieren die Links?
- [x] Sind alle Bilder richtig eingebunden?
- [x] funktioniert der R-Code und sehen die Plots richtig aus?
- [x] Tauchen irgendwo Warnungen etc auf, die dort nicht sein sollten?
- [x] Sind Textpassagen in der Randnotiz, die eigentlich in den Haupttext gehören?

Falls Fehler auffallen:

1. Wenn es ein einfacher Fehler ist (z.B. Schreibfehler, Überschrift auf der falschen Ebene, ...), dann können diese gerne direkt in der .qmd Datei behoben werden.
2. Wenn es kompliziertere Fehler sind oder Du nicht weißt, wie man den Fehler lösen kann, dann bitte unten einen Kommentar schreiben und mich mit @jhorzek erwähnen. Dann schaue ich, ob ich das Problem lösen kann.

Hinweis: Ich habe einige Überschriften angepasst (z.B. habe "## 1. Überschrift" zu "## Überschrift" geändert). Diese Anpassungen bitte nicht rückgängig machen!

**Comment by behnkec** [comment]
- [ ] 'Einleitung' als Überschrift?
- [ ] Einleitung aside: Link
- [ ] Einleitung Tabelle: Linearität etc. fett mit <b
- [ ] Link Lowess fit Line -> soll verlinkbar sein, aber nicht selbst ein Link
- [ ] 14.2 erste Zeile Zeilenumbruch vor e
- [ ] 14.3.1 Toggle Exkurs Quantifizierung: Achtung formatieren
- [ ] 14.3.2 Toggle Exkurs WLS: Achtung formatieren, beim zweiten Mal Achtung ganzen Absatz einrücken
- [ ] 14.4.1.1.1 Exkurs Grafische: **Warning** entfernen 2x
- [ ] 14.4.1.2.1 **Warnung** entfernen ICCest
- [ ] 14.4.1.2.1 aside weiter oben
- [ ] 14.4.1.2.2 Warning entfernen
- [ ] 14.5.1.1.1 Toggle reale und erwartete Dichtefunktion in orange und grün
- [ ] 14.5.2.1.1 library(car) -> echo=false
- [ ] 14.5.3 Person 50 rot und gestrichelte Linie in blau
- [ ] 14.5.3.1.1 extreme Abweichung in rot
