### ISSUE TITLE
Sind alle Missings zufällig?-Abschnitt als separates Markdown

### ISSUE THREAD

**Issue by vs723** [Methods-Berlin/RLernplattform#47]
Sollte dann als eigenen Abschnitt in part: "Vertiefungen zu den Veranstaltungen Methodenlehre I und II" eingefügt & entsprechend aus dem dazugehörigen Abschnitt "Fehlende Werte" aus part: "Einführung in R" genommen werden.

**Comment by behnkec** [comment]
@jhorzek Wie wollen wir hier mit den Abschnitten Literaturempfehlungen, FAQ und Übungen umgehen? Sollen die in das neue Markdown oder im alten bleiben oder beides?
Die Literaturempfehlungen würde ich vielleicht in beiden lassen. Bei den anderen beiden war ich mir nicht sicher, ich glaube eine Doppelung fänd ich an der Stelle blöd

**Comment by behnkec** [comment]
- [ ] neues Dokument erstellen
- [ ] Abschnitt hinzufügen 
- [ ] -> Sind alle Missings zufällig
- [ ] -> FAQ?
- [ ] -> Übungen?
- [ ] Dependencies korrigieren
- [ ] alten Abschnitt löschen

**Comment by jhorzek** [comment]
Ich würde die Literaturempfehlungen, FAQ und Übungen in das neue Markdown verschieben. Auf den ersten Blick scheinen die sich alle mit fortgeschrittenen Themen zum Umgang mit Missings zu beschäftigen; ich denke sie passen daher auch besser in das separate Markdown. Der erste Teil von Kapitel 9 "Fehlende Werte" bespricht dagegen eher den Umgang mit Missings in R (Codierung etc.). Ich fände es aber auch OK, die Literatur in beidem zu lassen.
