### ISSUE TITLE
Tabelle funktioniert nicht

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#50]
https://github.com/Methods-Berlin/RLernplattform/blob/82241f64d19878bf3b058ef602ba059132a7fb6e/Einfuehrung_in_R.qmd#L414

Die LaTeX Gleichungen werden nicht korrekt dargestellt.

**Comment by behnkec** [comment]
https://community.rstudio.com/t/problems-with-kable-and-escape-false/43048/4
