### ISSUE TITLE
Publizieren der Webseite

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RLernplattform#54]
Ich habe das Gefühl, dass wir gerade etwas davon zurückgehalten werden, dass die Webseite nicht online ist und es daher noch relativ kompliziert ist, das Projekt zu bearbeiten. Wir hatten bereits diskutiert, dass wir das Projekt veröffentlichen, aber noch nicht weiter auf dieses hinweisen könnten. Das würde es uns ermöglichen, die aktuelle Version der Webseite einfach im Browser zu betrachten und Anpassungen vorzunehmen, ohne jedes mal die Doc-Datei herunterladen zu müssen. 

Ich denke, es spricht eigentlich nichts mehr dagegen, das Projekt zu veröffentlichen. Was denkt ihr?

**Comment by Methods-Berlin** [comment]
Die Webseite ist jetzt online!
https://methods-berlin.github.io/RLernplattform/
