### ISSUE TITLE
Finaler Vergleich 

### ISSUE THREAD

**Issue by behnkec** [Methods-Berlin/RLernplattform#94]
- [x] nochmal alle Kapitel auf Fehler kontrollieren
- [x] Issues zu Vergleichen abschließen

**Comment by behnkec** [comment]
@jhorzek gibt es noch weitere Dinge, die wir tun müssen, um eine erste ferste Version zu haben?

**Comment by jhorzek** [comment]
Mir fällt sonst auch nichts mehr ein. Willst Du noch den renv-Branch in den main Branch mergen, bevor wir den finalen Vergleich vornehmen? Oder würdest Du damit noch warten wollen? Von mir aus können wir den gerne mergen; im Notfall kommen wir ja immer zu früheren Versionen zurück.

**Comment by jhorzek** [comment]
Ja, sehr gerne! Ich war micht nicht sicher, was hier der aktuelle Stand war

**Comment by behnkec** [comment]
@jhorzek bei Einführung: Datentypen ist die Fußnote der Tabelle irgendwie komisch formatiert, ich habe es aber nicht geschafft, das zu verändern. Hast du ne Idee?

**Comment by jhorzek** [comment]
Gute Frage! Ich habe leider keine Ahnung, woran das liegt. Ich kann das Problem lokal auch nicht reproduzieren. Interessanterweise ist der html-code, den unsere GitHub Action generiert anders als der, den das Projekt bei mir lokal erstellt. Ich würde das erst mal ignorieren und hoffen, dass sich das Problem von alleine löst, wenn wir die Pakete irgendwann mal updaten. Alternativ könnten wir die footnotes auch aus der Tabelle rausnehmen und einfach als Text hinter die Tabelle kopieren. Wie sieht die Seite bei aus, wenn Du diese lokal erstellst?

**Comment by behnkec** [comment]
@jhorzek Bei mir sieht es genauso aus wie remote

**Comment by behnkec** [comment]
Bis auf die zwei Pull requests (und die Fußnoten), die noch ausstehen sieht jetzt alles gut aus.

**Comment by jhorzek** [comment]
Super, vielen Dank!! Interessant, dass die Webseite bei Dir auch anders aussieht als bei mir. Ich wollte demnächst mal R und Rstudio aktualisieren, vielleicht hat es damit was zu tun. Ich würde hoffen, dass das einfach ein Bug ist, der schnell gelöst wird.
